name: learn-github-actions
run-name: Running Tests from Express
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Clone Express Repo
        uses: actions/checkout@v2
        with:
          repository: expressjs/express
          path: express

      - name: "Test"
        working-directory: express
        run: ls -la